### ISSUE TITLE
Missing Split labels

### ISSUE THREAD

**Issue by Clare72** [VirtualFlyBrain/vfb-prod#14]
According to [neo4j2owl-config.yaml](https://github.com/VirtualFlyBrain/vfb-prod/blob/master/neo4j2owl-config.yaml#L129), descendants of VFBext:0000010 ("intersectional expression pattern") should get the Split label.

There are many subclasses of VFBext:0000010 in the [triplestore](http://ts.p2.virtualflybrain.org/rdf4j-workbench/repositories/vfb/query)
```
SELECT * 
WHERE { ?s ?p <http://purl.obolibrary.org/obo/fbbt/vfb/VFBext_0000010>}
```

But these do not get the Split label 
```MATCH (n) WHERE n.short_form="VFBexp_FBti0186572FBti0129742" RETURN n```

In fact, there are no nodes with the Split label in pdb-dev
```MATCH (s:Split) RETURN s.iri```

**Comment by Robbie1977** [comment]
FYI Jar file currently lives here: https://github.com/VirtualFlyBrain/vfb-pipeline-dumps/tree/vfb_pipeline/scripts
